#!/usr/bin/env python3
"""extract_helpers.py <kenshifp_client.c> <out.h> name...: copy the named top-level `static` functions
(definition through the closing brace at column 0, or one-line bodies) out of the KenshiFP client source,
so the offline replay compiles the REAL helpers (quat math etc.) instead of re-implementations."""
import re, sys
src = open(sys.argv[1], encoding='utf-8', errors='replace').read().split('\n')
out = ['/* generated by extract_helpers.py from %s: do not edit */' % sys.argv[1]]
for name in sys.argv[3:]:
    pat = re.compile(r'^static\b[^;(]*\b' + re.escape(name) + r'\s*\(')
    for i, l in enumerate(src):
        if pat.match(l) and not l.rstrip().endswith(';'):
            if l.count('{') and l.count('{') == l.count('}'):
                out.append(l); break
            j = i
            while j < len(src) and src[j] != '}': j += 1
            out.extend(src[i:j + 1]); break
    else:
        sys.exit('extract_helpers: %s not found' % name)
open(sys.argv[2], 'w').write('\n'.join(out) + '\n')
