#!/usr/bin/env python3
"""ledger.py -- animation lab catch-rate ledger: who found each flaw first, per build and per flaw class.

Reads the rows of STATUS.md "Misses" (pose flaws) and SETUP_MISSES.md (take/setup flaws) in the harness docs/animlab and
rewrites the table between `<!-- ledger:start -->` and `<!-- ledger:end -->` in STATUS.md "Catch-rate ledger".
Finder per row (first match wins): an explicit `found:lab|review|shay|game|mutation` tag anywhere in the row; else
"Shay" / "ticket A" -> shay; "coordinator review" / "(coordinator" / "review of" / "review:" -> review; "lab-found" /
"lab #" / "found by lab" / "mutation" -> lab; anything else = the game (rows/takes/the fixer's runs) found it and the lab
missed it -> game. A Misses row by definition is a flaw the lab did NOT catch first, so the "lab" column counts only
lab-found rows; regress/gate FAILs that stopped a build before filming are counted from gate logs (`--gate-dir`).
Class: setup (SETUP_MISSES + take:/open ground/cursor rows), sword-pose (E1/E5/E6/sword/blade/guard/elbow/hinge/arc),
crossbow (C1-C3/X1/X7/crossbow/bolt/stock), zoom (Z1/zoom), lab-infra (lab build/replay/faithfulness/jitter under).
Usage: ledger.py [--docs <harness docs/animlab>] [--gate-dir /root/animlab-gate] [--print]
"""
import argparse, collections, glob, os, re, sys

DOCS = '/mnt/c/KenshiModding/Kenshi-Automation-Harness/docs/animlab'
FINDERS = ('lab', 'review', 'shay', 'game')


def rows(path, section=None):
    out, on = [], section is None
    for l in open(path, encoding='utf-8'):
        if section and l.startswith('## '):
            on = l.strip() == section
            continue
        if on and l.startswith('- 20') and l.count('|') >= 4:
            out.append(l.strip()[2:])
    return out


def finder(r):
    m = re.search(r'found:(lab|review|shay|game|mutation)', r)
    if m: return 'lab' if m.group(1) == 'mutation' else m.group(1)
    lo = '|'.join(r.split('|')[:3]).lower()   # date | point | what showed (the status column names checks/mutations)
    if 'shay' in lo or 'ticket a' in lo: return 'shay'
    if 'coordinator review' in lo or '(coordinator' in lo or 'review of' in lo or 'review:' in lo or 'pending (review)' in lo: return 'review'
    if 'lab-found' in lo or 'lab #' in lo or 'found by lab' in lo or 'mutation' in lo: return 'lab'
    # 2026-10-10: the coordinator's frame-by-frame review of the vm-rework / f36 videos (regress steps 23-26 history)
    if re.search(r'vm-rework|zoom-sweep|sword-z25-block|turret-fp|anim-sword-e6|refilm', lo): return 'review'
    return 'game'


def klass(point, setup):
    p = point.lower()
    if setup or p.startswith('take') or 'open ground' in p or 'cursor' in p: return 'setup'
    if re.search(r'\bz1\b|zoom', p): return 'zoom'
    if re.search(r'\b(c[123]|x[17])\b|crossbow|bolt|stock', p): return 'crossbow'
    if re.search(r'lab build|faithful|jitter under|replay vs game', p): return 'lab-infra'
    return 'sword-pose'


def build_of(r):
    f = r.split('|'); rest = '|'.join(f[3:-1])   # recording + build columns (free text may hold extra '|'), not status
    m = (re.search(r'\b([0-9A-F]{8})\b', rest) or re.search(r'\b([0-9a-f]{7})\b', rest)
         or re.search(r'build (Oct \d+ [0-9:]+)', rest))
    return m.group(1) if m else '-'


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--docs', default=DOCS); ap.add_argument('--gate-dir', default='/root/animlab-gate')
    ap.add_argument('--print', action='store_true'); a = ap.parse_args()
    st = os.path.join(a.docs, 'STATUS.md'); sm = os.path.join(a.docs, 'SETUP_MISSES.md')
    R = [(r, False) for r in rows(st, '## Misses (game found, lab missed)')]
    if os.path.exists(sm): R += [(r, True) for r in rows(sm)]
    byb = collections.OrderedDict(); byc = collections.OrderedDict()
    for r, setup in R:
        f = [x.strip() for x in r.split('|')]
        if 'DROPPED' in f[-1]: continue
        who, k, b = finder(r), klass(f[1], setup), build_of(r)
        key = (f[0], b)
        byb.setdefault(key, collections.Counter())[who] += 1
        byc.setdefault(k, collections.Counter())[who] += 1
    gate = collections.Counter()
    for p in glob.glob(os.path.join(a.gate_dir, 'result-*.txt')):
        l = open(p).read()
        if ' FAIL ' in l and 'flipped=' in l and 'flipped=none' not in l: gate['flip'] += 1
    hdr = '| %s | lab | review | Shay | game | total |\n|---|---|---|---|---|---|\n'
    out = ['Generated by `components/KenshiFP/animlab/ledger.py` (KenshiModding) from the Misses + SETUP_MISSES rows; '
           'do not edit by hand. "game" = found in game rows/takes after the lab passed; "lab" = the lab found it first.', '',
           '**Per date / build** (build = column 5 of the row, `-` = take/setup rows without a build)', '', hdr % 'date / build']
    tot = collections.Counter()
    for (d, b), c in byb.items():
        out.append('| %s %s | %d | %d | %d | %d | %d |\n' % (d, b, c['lab'], c['review'], c['shay'], c['game'], sum(c.values())))
        tot.update(c)
    out.append('| **all** | %d | %d | %d | %d | %d |\n' % (tot['lab'], tot['review'], tot['shay'], tot['game'], sum(tot.values())))
    out += ['', '**Per flaw class**', '', hdr % 'class']
    for k, c in sorted(byc.items()):
        out.append('| %s | %d | %d | %d | %d | %d |\n' % (k, c['lab'], c['review'], c['shay'], c['game'], sum(c.values())))
    n = sum(tot.values())
    out += ['', 'Lab catch rate (lab-first / all flaws): %d/%d = %.0f%%; gate runs that blocked a build on a returned miss: %d.'
            % (tot['lab'], n, 100.0 * tot['lab'] / max(1, n), gate['flip'])]
    table = ''.join(x if x.endswith('\n') else x + '\n' for x in out)
    if a.print:
        print(table); return 0
    s = open(st, encoding='utf-8').read()
    i, j = s.find('<!-- ledger:start -->'), s.find('<!-- ledger:end -->')
    if i < 0 or j < 0:
        print('ledger: markers missing in STATUS.md (add a "## Catch-rate ledger" section with <!-- ledger:start --> / <!-- ledger:end -->)')
        return 1
    s = s[:i] + '<!-- ledger:start -->\n' + table + s[j:]
    open(st, 'w', encoding='utf-8').write(s)
    print('ledger: %d flaws, lab %d review %d Shay %d game %d -> %s' % (n, tot['lab'], tot['review'], tot['shay'], tot['game'], st))
    return 0


if __name__ == '__main__':
    sys.exit(main())
