#!/bin/bash
# python3 shim (4080 rig, C:\KAH\bin\python3): the Windows Python 3.13 that has PIL (WSL-style scripts call python3)
exec /c/Users/Shay/AppData/Local/Programs/Python/Python313/python.exe "$@"
